# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
  python: python3.11

exclude: .*migrations\/.* , settings\/.*, .platform\/.*, .cloudformation\/.*, .ebextensions\/.*, .dockerfile, .docker\/.*, .*.app.py, '.*static\/.*', '.*templates\/.*', .*.__init__.py, .*.md,

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-ast
      - id: check-json
      - id: pretty-format-json
        args: [--autofix]
      - id: check-toml

      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-private-key
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff
        args: ["--config", "ruff.toml", "--fix"]

  # - repo: https://github.com/google/yapf.git
  #   rev: "v0.40.2"
  #   hooks:
  #     - id: yapf

  - repo: https://github.com/hadialqattan/pycln
    rev: v2.2.2
    hooks:
      - id: pycln

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
