# Generated by Django 5.0.7 on 2025-03-05 11:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="share",
            name="recieved_by",
            field=models.ManyToManyField(
                related_name="read_notification", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
