# Generated by Django 5.0.7 on 2025-03-06 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0002_share_recieved_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="share",
            name="recieved_by",
        ),
    ]
