# Generated by Django 5.0.7 on 2025-03-12 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0003_remove_share_recieved_by"),
        ("storage", "0016_alter_drive_size_alter_drive_used"),
    ]

    operations = [
        migrations.AddField(
            model_name="share",
            name="parent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="root_share",
                to="storage.object",
            ),
        ),
    ]
