# Generated by Django 5.0.7 on 2024-08-07 15:38

import uuid

import django.utils.timezone
import storage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bucket",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=2000,
                        null=True,
                        verbose_name="AWS bucket name",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True, null=True, verbose_name="AWS bucket URL"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Drive",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=2000,
                        null=True,
                        verbose_name="Drive's name",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("personal", "personal"), ("shared", "shared")],
                        default="shared",
                        verbose_name="Drive type",
                    ),
                ),
                (
                    "size",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Drive size (kb)"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Object",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "name",
                    models.CharField(max_length=2000, verbose_name="File/Folder name"),
                ),
                ("is_directory", models.BooleanField(default=False)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=storage.models.upload_file_to_user_drive,
                        verbose_name="File",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        blank=True,
                        max_length=2000,
                        null=True,
                        verbose_name="AWS path : key",
                    ),
                ),
                (
                    "filesystem_path",
                    models.CharField(
                        blank=True,
                        max_length=2000,
                        null=True,
                        verbose_name="Local path",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(default=dict, verbose_name="File metadata"),
                ),
                (
                    "size",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Size of the file/directory (kb)",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
