# Generated by Django 5.0.7 on 2024-08-07 16:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="drive",
            options={},
        ),
        migrations.AddConstraint(
            model_name="drive",
            constraint=models.UniqueConstraint(
                condition=models.Q(("type", "PERSONAL")),
                fields=("owner",),
                name="unique_personal_drive_per_user",
            ),
        ),
    ]
