# Generated by Django 5.0.7 on 2024-08-08 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0007_remove_drive_unique_personal_drive_per_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="drive",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
