# Generated by Django 5.0.7 on 2024-08-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0009_object_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="drive",
            name="bucket",
        ),
        migrations.AddField(
            model_name="object",
            name="content",
            field=models.ManyToManyField(to="storage.object"),
        ),
        migrations.DeleteModel(
            name="Bucket",
        ),
    ]
