# Generated by Django 5.0.7 on 2024-08-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0010_remove_drive_bucket_object_content_delete_bucket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="object",
            name="content",
            field=models.ManyToManyField(blank=True, null=True, to="storage.object"),
        ),
    ]
