# Generated by Django 5.0.7 on 2024-08-15 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0011_alter_object_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="object",
            name="content",
        ),
    ]
