# Generated by Django 5.0.7 on 2024-08-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0013_object_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="object",
            name="content",
            field=models.ManyToManyField(
                blank=True, related_name="in_directory", to="storage.object"
            ),
        ),
    ]
