# Generated by Django 5.0.7 on 2024-12-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0014_alter_object_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="object",
            name="path",
            field=models.CharField(
                blank=True,
                default="new",
                max_length=2000,
                null=True,
                verbose_name="AWS path : key",
            ),
        ),
    ]
