# Generated by Django 5.0.7 on 2025-03-05 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
        ("share", "0002_share_recieved_by"),
        ("storage", "0016_alter_drive_size_alter_drive_used"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="drivenotification",
            name="read",
        ),
        migrations.AlterField(
            model_name="drivenotification",
            name="drive",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="storage.drive",
            ),
        ),
        migrations.RemoveField(
            model_name="drivenotification",
            name="share",
        ),
        migrations.AddField(
            model_name="drivenotification",
            name="share",
            field=models.ManyToManyField(
                related_name="user_notifications", to="share.share"
            ),
        ),
    ]
