# Generated by Django 5.0.7 on 2025-03-06 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_remove_drivenotification_share_and_more"),
        ("share", "0003_remove_share_recieved_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="drivenotification",
            name="share",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_notifications",
                to="share.share",
            ),
        ),
    ]
