name: Build and Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build, Push to Docker Hub, and Deploy to EC2
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: adinoyi/conduit 
      TAG: latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:$TAG -f ./docker/production.Dockerfile .

      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME:$TAG

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Deploy to EC2 via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF

            cd ~

            echo "Stopping containers..."
            sudo docker-compose -f production.compose.yml down

            echo "Removing old image..."
            sudo docker rmi $IMAGE_NAME:$TAG || true

            echo "Pulling latest image..."
            sudo docker pull $IMAGE_NAME:$TAG

            echo "Starting containers..."
            sudo docker-compose -f production.compose.yml up -d
          EOF

