name: Deploy to EC2 on main push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Run deployment commands on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~

            echo "Stopping containers..."
            sudo docker-compose -f production.compose.yml down

            echo "Removing old image..."
            sudo docker rmi adinoyi/conduit:latest || true

            echo "Pulling latest image..."
            sudo docker pull adinoyi/conduit:latest

            echo "Starting containers..."
            sudo docker-compose -f production.compose.yml up -d
          EOF

